### ISSUE TITLE
Make it INGAME

### ISSUE THREAD

**Issue by SupinePandora43** [Metastruct/gmod-monaco#2]
vgui:DHTML maybe...

**Comment by Zeni44** [comment]
![image](https://user-images.githubusercontent.com/11852198/83034016-12aa8800-a038-11ea-9b3f-8376cf310a42.png)

**Comment by SupinePandora43** [comment]
what?

**Comment by Earu** [comment]
Did it cross your mind that maybe this is meant to be used **in-game**?

**Comment by ThatLing** [comment]
help i get error

**Comment by SupinePandora43** [comment]
// i never had so many participiants at same time writing
// earu its you, hewwo
why it can't be used ingame?

**Comment by Earu** [comment]
It __can__ be used in-game.
Here are examples:
https://github.com/JustMrPhoenix/Noir
https://github.com/Earu/EasyChat/blob/master/lua/easychat/modules/lua_tab.lua

**Comment by SupinePandora43** [comment]
is there any chance to get it in vscode? as extension on marketplace?

**Comment by Cynosphere** [comment]
Monaco is already the base of VSCode as it is
